version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_DATABASE: Cafewhere_db
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/Cafewhere
      - public-data:/Cafewhere/public
      - tmp-data:/Cafewhere/tmp
      - log-data:/Cafewhere/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/Cafewhere/public
      - tmp-data:/Cafewhere/tmp
    ports:
      - 80:80

volumes:
  # mysql-data:
  public-data:
  tmp-data:
  log-data: